project_hotel/hotel/urls.py
from django.urls import path, re_path
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path(r'rooms/', views.Room_ListView.as_view(), name='rooms'),
    path(r'rooms/<pk>', views.room_detail, name='room-detail'),
    path(r'my_reservations', views.user_reservation, name='user_reserv'),
    path('create_reservation/<int:room_id>/', views.create_reservation, name='create-reservation'),
    path('reservation/<int:reservation_id>/delete/', views.delete_reservation, name='delete-reservation'),
    path('reservation/<int:reservation_id>/', views.reservation_detail, name='reservation-detail'),

    path('search/', views.search_rooms, name='search'),

    path('about', views.about_the_hotel, name='about-the-hotel')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_hotel/project_hotel/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('hotel/', include('hotel.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.home, name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_hotel/hotel/models.py
from django.db import models
from django.shortcuts import reverse

from django.contrib.auth.models import User

from django.utils import timezone
import datetime

class Room(models.Model):
    title = models.CharField(max_length = 200)
    number = models.IntegerField()
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    sleeping_places = models.IntegerField(default=1, choices=[(i, int(i)) for i in range(1, 6)])
    is_available = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('room-detail', kwargs={'pk': self.pk})

class Reservation(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    guest_name = models.CharField(max_length = 100, default='Guest')
    check_in_date = models.DateField()
    check_out_date = models.DateField()
    is_active = models.BooleanField(default=True)
    add_to_profile = models.ManyToManyField(User, related_name='user_reserv', blank=True,)

    def __str__(self):
        return self.guest_name

    def get_absolute_url(self):
        return reverse('reservation-detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        if self.check_out_date < timezone.now().date():
            self.is_active = False
        existing_reservations = Reservation.objects.filter(room=self.room, is_active=True)
        for reservation in existing_reservations:
            if reservation.check_in_date <= self.check_in_date <= reservation.check_out_date or reservation.check_in_date <= self.check_out_date <= reservation.check_out_date:
                raise Exception("Room is already reserved for the specified dates")
        super().save(*args, **kwargs)


class RoomImage(models.Model):
    image = models.ImageField(upload_to='room_images/', blank=True, null=True)
    product = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='images')

    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in RoomImage._meta.fields]

project_hotel/hotel/forms.py
from django.forms import ModelForm, ValidationError
from django import forms
from datetime import date
from .models import Reservation

class SearchForm(forms.Form):
    date_in = forms.DateField(initial=date.today)
    date_out = forms.DateField(initial=date.today)


class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ['guest_name', 'check_in_date', 'check_out_date']
        widgets = {
            'check_in_date': forms.DateInput,
            'check_out_date': forms.DateInput,
        }
        initial = {
            'check_in_date': date.today(),
            'check_out_date': date.today(),
        }

project_hotel/hotel/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from .models import Room, Reservation

from django.utils import timezone

from .forms import SearchForm, ReservationForm
from .utils import find_available_rooms

class Room_ListView(LoginRequiredMixin, generic.ListView):
    model = Room
    context_object_name = 'room_list'

    queryset = Room.objects.all()

    template_name = 'hotel/room_list_.html'

    paginate_by = 6


def room_detail(request, pk):
    room = get_object_or_404(Room, pk=pk)
    return render(request, 'room_detail.html', {'room': room, 'pk': pk})


@login_required
def create_reservation(request, room_id):
    room = get_object_or_404(Room, id=room_id)

    if request.method == 'POST':
        form = ReservationForm(request.POST)
        if form.is_valid():
            reservation = form.save(commit=False)
            reservation.room = room
            reservation.save()
            reservation.add_to_profile.add(request.user)
            return render(request, 'reservation_detail.html', {'reservation': reservation})
    else:
        form = ReservationForm()

    return render(request, 'reservation_form.html', {'form': form})

def reservation_detail(request, reservation_id):
    reservation = get_object_or_404(Reservation, id=reservation_id)
    return render(request, 'reservation_detail.html', {'reservation': reservation})


def user_reservation(request):
    reserv = Reservation.objects.filter(add_to_profile=request.user)
    #total_price = cart_items.aggregate(total=Sum(F('product__price') * F('quantity')))['total']
    return render(request, 'user_reservation.html', {'reserv': reserv})


def delete_reservation(request, reservation_id):
    reservation = get_object_or_404(Reservation, id=reservation_id)
    if reservation.check_in_date > timezone.now().date():
        if request.user in reservation.add_to_profile.all():
            if request.method == 'POST':
                reservation.delete()
                return redirect('user_reserv')

            return render(request, 'reservation_delete.html', {'reservation': reservation})

    return redirect('reservation-detail', reservation_id=reservation_id)


def search_rooms(request):
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            date_in = form.cleaned_data['date_in']
            date_out = form.cleaned_data['date_out']
            available_rooms = find_available_rooms(date_in, date_out)
            if date_out < date_in or date_in < timezone.now().date():
                form = SearchForm()
                return render(request, 'search_form.html', {'form': form})
            else:
                return render(request, 'search_results.html', {'available_rooms': available_rooms, 'date_in': date_in, 'date_out': date_out})
    else:
        form = SearchForm()
        return render(request, 'search_form.html', {'form': form})

def about_the_hotel(request):
    return render(request, 'about_the_hotel.html')

project_hotel/hotel/templates/about_the_hotel.html
{% extends "base_generic.html" %}

{% block content %}

<div class="background2">
    <table class="baza">
        <tr><th class="th-baza"><h1 style="font-size: 40px; background-color: rgba(0,0,0,0.3);"> О НАС </h1></th></tr>
    </table>
</div>
<div class="complex">
    <div class="complex-1">
        <table>
            <tr>
                <th>
                    <img src="/static/media/complex.jpg" class="image-home" align="left">
                </th>
                <th style="width: 500px; text-align: left;">
                    <br>
                    <p style="font-size: 12px;">«Турист» — это туристическая база, в 40 км от города Гродно, на территории которого расположено 6 домиков. Это стильные, современные, продуманные до мелочей номера для размещения, которые перенесут вас в новую реальность. Загородные домики комфортные,  для отдыха вдвоем, семьей или даже большой компанией (при условии бронирования сразу нескольких).</p>
                </th>
            </tr>
        </table>
        <br>
        <hr>
        <p style="font-size: 15px;">Наша турбаза расположена на берегу озера «Белое», что обеспечивает огромное количество вариантов времяпрепровождения как зимой, так и летом. Это могут быть прогулки, катание на катамаранах, сап-досках и лодках, купание и отдых на пляже. Зимой мы организуем безопасное катание на коньках по поверхности озера, прокат лыж и другого спортивного инвентаря.
            Если вы рассматриваете вариант отдыха с детьми, это тоже к нам в турбазу «Турист»! На территории есть детский городок, оборудованный увлекающими детей снарядами и конструкциями.
            Мы позаботились о том, чтобы ваше пребывание было максимально комфортным и не требующим каких-то бесконечных дополнений — вы приезжаете, и сразу окунаетесь в атмосферу отдыха.
        </p>
        <br>
        <a href="{% url 'home' %}" class="button">НА ГЛАВНУЮ </a>
        <hr>
    </div>
</div>

{% endblock %}

project_hotel/hotel/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %} <title> Отель-Химик </title> {% endblock %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>


    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <script>
         $(document).ready(function() {
            $("#id_date_in").datepicker({
                dateFormat: "dd.mm.yy"
            });
            $("#id_date_out").datepicker({
                dateFormat: "dd.mm.yy"
            });
        });
    </script>

</head>

<body>
    <div >
        <!--# Navbar #-->
        {% block sidebar %}
        <nav class="stick">
            <nav class="nav">
                <div class="navbar-logo"></div>
                {% if user.is_authenticated %}
                <ul class="navbar-menu">
                    <li>
                        <a  href="{% url 'profile' %}">{{ user.get_username }}</a>
                    </li>
                    <li>
                        <a  href="{% url 'logout'%}?next={{request.path}}">Выход</a>
                    </li>
                </ul>
                {% else %}
                <ul class="navbar-menu">
                    <li>
                        <a  href="{% url 'register_request'%}?next={{request.path}}">Регистрация</a>
                    </li>
                    <li>
                        <a  href="{% url 'login'%}?next={{request.path}}">Вход</a>
                    </li>
                </ul>
                {% endif %}
            </nav>
            <nav class="navbar">
                <table class="table-navbar">
                    <tr class="navbar-menu">
                        <th><a  href="{% url 'about-the-hotel' %}">О НАС</a></th>
                        <th><a  href="{% url 'rooms' %}">ДОМА</a></th>
                        <th><a href="#">ДОСУГ</a></th>
                        <th><a href="#">КОНТАКТЫ</a></th>
                        <th>
                            <form class="form-inline" action="{% url 'search' %}" method="get">
                                <button class="btn " type="submit">поиск по дате</button>
                            </form>
                        </th>
                    </tr>
                </table>
            </nav>
        </nav>
        {% endblock %}
        <!--# Navbar #-->
        <div>
            {% block content %}{% endblock %}
        </div>
    </div>
</body>

project_hotel/hotel/templates/home.html
{% extends "base_generic.html" %}


{% block content %}
<div class="background">
    <table class="baza">
        <tr><th class="th-baza"><h2> ТУРИСТИЧЕСКАЯ БАЗА «ХИМИК» </h2></th></tr>
        <tr><th class="th-baza"><h2> В ГРОДНЕНСКОЙ ОБЛАСТИ </h2></th></tr>
        <tr><th class="th-baza"><h3> УВИДЕТЬ ОДИН РАЗ, ВЛЮБИТЬСЯ НАВСЕГДА </h3></th></tr>
    </table>
</div>
<div class="complex">
    <div class="complex-1">
        <img src="/static/media/complex.jpg" class="image-home" align="left">
        <h5>О НАШЕМ КОМПЛЕКСЕ:</h5>
        <ul style="font-size: 12px;">
            <li>- Туристическая база "Химик" расположена в 40 км. от города Гродно. Это живописнейшее уединённое место в сосновом бору, на берегу озера Белое.</li>
            <li>- Отдых на турбазе многогранен и способен удовлетворить пожелания различных возрастных категорий. Турбаза идеально подходит как для семейного отдыха и отдыха выходного дня, так и для проведения корпоративных мероприятий, организации турслётов.</li>
            <li>- В летнее время организуются семейные заезды по 12 дней с предоставлением путёвок для различных категорий граждан (в стоимость включено питание и проживание).</li>
            <li>- Неимоверная красота природы, вкуснейшая домашняя кухня, доброжелательный персонал - всё это ждёт Вас на туристической базе "Химик"!</li>
        </ul>
        <br>
        <a href="#" class="button">ПОДРОБНЕЕ</a>
        <br>
        <br>
        <h5>РАЗМЕЩЕНИЕ</h5>
        <p style="font-size: 12px;">Отдых на турбазе «Химик» предусматривает возможность размещения в отдельно стоящих домиках разной степени комфортности. Наша туристическая база включает 10 домов и, позволяя удобно разместиться как небольшой компании, так и делегации побольше (при условии аренды сразу нескольких средств размещения). Одно из основных преимуществ наших домиков – детально продуманное оснащение: в каждом из них, есть все необходимое, начиная с мебели, постельных принадлежностей и текстиля и заканчивая такими деталями, как бокалы и посуда. И все это идеально подобрано и вписано в стильный интерьер, продуманный талантливыми дизайнерами.</p>
    </div>
</div>
<div class="complex">
    <div class="complex-1">
        <table>
            <tr>
                <th style="width: 500px; text-align: left;">
                    <h5 style="margin-left: 50px;">ДОМИК НОМЕР 1</h5>
                    <br>
                    <ul style="font-size: 12px;">
                        <li>- Одноэтажный домик на 4 мест</li>
                        <li>- 2 комнаты отдыха, кухня оборудованная бытовой техникой, плита, холодильник, душ, туалет, телевидение, кондиционер, закрытая веранда.</li>
                        <li>- Холодная и горячая вода, отопление.</li>
                        <li>- Безбарьерная среда.</li>
                    </ul>
                </th>
                <th>
                    <img src="/static/media/home1.jpg" class="image-home" align="left">
                </th>
            </tr>
            <tr style="height: 40px;">
                <th>
                    <h6>Стоимость – 400 рублей сутки</h6>
                </th>
                <th>
                    <form class="form-inline" action="{% url 'search' %}" method="get">
                        <button class="btn " type="submit">забронировать</button>
                    </form>
                </th>
            </tr>

            <tr>
                <th>
                    <img src="/static/media/home2.jpg" class="image-home" align="left">
                </th>
                <th style="width: 500px; text-align: left;">
                    <h5 style="margin-left: 50px;">ДОМИК НОМЕР 2</h5>
                    <br>
                    <ul style="font-size: 12px;">
                        <li>- Одноэтажный домик на 5 мест.</li>
                        <li>- 2 комнаты отдыха, кухня оборудованная бытовой техникой, плита, холодильник, душ, туалет, телевидение, кондиционер, закрытая веранда.</li>
                        <li>- Холодная и горячая вода, отопление.</li>
                    </ul>
                </th>
            </tr>
            <tr style="height: 40px;">
                <th>
                    <form class="form-inline" action="{% url 'search' %}" method="get">
                        <button class="btn " type="submit">забронировать</button>
                    </form>
                </th>
                <th>
                    <h6>Стоимость – 420 рублей сутки</h6>
                </th>
            </tr>
            <tr>
                <th style="width: 500px; text-align: left;">
                    <h5 style="margin-left: 50px;">ДОМИК НОМЕР 3</h5>
                    <br>
                    <ul style="font-size: 12px;">
                        <li>- Одноэтажный домик на 6 мест</li>
                        <li>- 2 комнаты отдыха, кухня оборудованная бытовой техникой, плита, холодильник, душ, туалет, телевидение, кондиционер, закрытая веранда.</li>
                        <li>- Холодная и горячая вода, отопление.</li>
                        <li>- Безбарьерная среда.</li>
                    </ul>
                </th>
                <th>
                    <img src="/static/media/home3.jpg" class="image-home" align="left">
                </th>
            </tr>
            <tr style="height: 40px;">
                <th>
                    <h6>Стоимость – 450 рублей сутки</h6>
                </th>
                <th>
                    <form class="form-inline" action="{% url 'search' %}" method="get">
                        <button class="btn " type="submit">забронировать</button>
                    </form>
                </th>
            </tr>
        </table>
        <a href="{% url 'rooms' %}" class="button">ПОСМОТРЕТЬ ЕЩЕ </a>
        <hr>
    </div>
</div>
<div class="complex">
    <div class="complex-1">
        <br>
        <h5>КАК ПРОВЕСТИ ВРЕМЯ?</h5>
        <br>
        <p>Наша туристическая база «Химик»   на берегу озера,  в лесу – это идеальный вариант для загородного отдыха на выходные или даже на 5-10 дней. Внушительное разнообразие вариантов времяпрепровождения обеспечит вас идеями по части того, чем можно заняться. Для полного расслабления у вас будет главное – красивая природа! Озерная гладь в обрамлении пышной растительности, вид на невероятные рассветы и закаты, гармоничный ландшафт – это то, что делает привлекательным загородный отдых зимой и летом. Прогулки на природе станут для вас источником накопления энергии и вдохновения! Добавьте к этому купание в озере (или катание по нему на коньках в зимнее время), «путешествия» на катамаранах, лодках, прокат байдарок,  игру в волейбол, футбол, бадминтон. Если перепробовать все это, можно и не заметить, как пролетят выходные!</p>
    </div>
</div>

{% endblock %}

project_hotel/hotel/templates/room_detail.html
{% extends "base_generic.html" %}

{% block content %}
<div  style="background-image: url('{{ room.images.first.image.url }}'); width: 1024px; image-width: 1024px; height: 576px; margin: auto; display: flex; align-items: center;" >
    <table class="baza">
        <tr><th class="th-baza"><h1 style="font-size: 30px; background-color: rgba(0,0,0,0.3);"> ДОМИК НОМЕР {{ room.number }} </h1></th></tr>
        <tr><th class="th-baza"><h1 style="font-size: 30px; background-color: rgba(0,0,0,0.3);"> НА ТУРБАЗЕ "ХИМИК" </h1></th></tr>
    </table>
</div>
<div class="complex">
    <div class="complex-1">
        <div style="width: 700px; margin: auto;">
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>

                <div class="carousel-inner">
                    {% for image in room.images.all %}
                    {% if forloop.first %}
                    <div class="carousel-item active">
                        <img class="d-block w-100" src="{{ image.image.url }}" style="max-width: 700px; max-height: 480px;" alt="First slide">
                    </div>
                    {% else %}
                    <div class="carousel-item">
                        <img class="d-block w-100" src="{{ image.image.url }}" style="max-width: 700px; max-height: 480px;" alt="First slide">
                    </div>
                    {% endif %}
                    {% endfor %}

                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
            <!-- Right Column -->
            <div class="right-column">

                <!-- Product Description -->
            <div>
                <br>
                <h2>{{ room.title }}</h2>
                <br>
            </div>
                <div class="product-description">
                    <H5>ВМЕСТИТЕЛЬНОСТЬ – {{ room.sleeping_places }} ЧЕЛОВЕКА  </H5>

                    <h4>Стоимость – {{ room.price }} BYN сутки</h4>
                    <br>
                </div>

                   <!-- Room Pricing -->
                <div>

                    <a href="{% url 'create-reservation' room_id=room.id %}" class="button">Забронировать</a>
                    <br><br>
                    {% if room.description %}
                    <h5>Описание:</h5>
                    <h5>{{ room.description }}</h5>
                    {% else %}
                    <h5>Описание пока что не добавлено </h5>
                    {% endif %}

                </div>
            </div>


    </div>
</div>
{% endblock %}

project_hotel/hotel/templates/search_form.html
{% extends "base_generic.html" %}

{% block content %}

<div class="background-search">
    <table class="baza">
        <tr><th class="th-baza"><h1 style="font-size: 30px; background-color: rgba(0,0,0,0.3);"> Поиск свободных домиков по дате: </h1></th></tr>
    </table>
</div>

<div class="complex">
    <div class="complex-1">
        <form action="" method="post">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input type="submit" value="Поиск" />

        </form>
    </div>
</div>

{% endblock %}

project_hotel/hotel/templates/search_results.html
{% extends "base_generic.html" %}
{% block content %}

<div class="background-search">
    <table class="baza">
        <tr><th class="th-baza"><h1 style="font-size: 30px; background-color: rgba(0,0,0,0.3);"> Свободные домики в интервале: с {{ date_in }} по {{ date_out }} </h1></th></tr>
    </table>
</div>

<div class="complex">
    <div class="complex-1">

        {% for room in available_rooms %}
        <table>
            <tr>
                <th>
                    <img src="{{ room.images.first.image.url }}" alt="{{ room.title }}" class="image-home" align="left">
                </th>
                <th style="width: 500px; text-align: left;">
                    <a style="margin-left: 50px; font-size: 17px; " href="{{ room.get_absolute_url }}" class="button">{{ room.title }}</a>
                    <br>
                    <br>
                    <ul style="font-size: 13px; ">
                        <li>- домик номер: {{ room.number }}</li>
                        <li>- спальных мест: {{ room.sleeping_places }}</li>
                        <li>- Холодная и горячая вода, отопление.</li>
                        <li>- Безбарьерная среда.</li>
                    </ul>
                </th>
            </tr>
            <tr style="height: 40px;">
                <th>
                    <h6>Стоимость – {{ room.price }} BYN сутки</h6>
                </th>
                <th>
                    <a href="{{ room.get_absolute_url }}" class="button">ПОДРОБНЕЕ</a>
                </th>
            </tr>
        </table>
        <hr>
        <br>
        {% empty %}
            <p class="list-group-item"> По запросу ничего не найдено </p>
        {% endfor %}
    </div>
</div>

{% endblock %}